services:
  haproxy:
    build: .  # Assuming your Dockerfile is in the same directory
    container_name: visionpay-haproxy
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # You might not need to explicitly mount these again if you COPY in Dockerfile
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./lua:/usr/local/etc/haproxy/lua:ro
      - ./errors:/usr/local/etc/haproxy/errors:ro
    environment:
      - TZ=UTC
    privileged: true
    user: root
